### ISSUE TITLE
Expected space/time?

### ISSUE THREAD

**Issue by dnbaker** [splatlab/cqf#1]
Very exciting work!

In comparing the Counting Quotient Filter to counting bloom filters and other probabilistic data structures, can you provide any numbers?

For example, the [Cuckoo Filter](https://www.cs.cmu.edu/~dga/papers/cuckoo-conext2014.pdf) paper (Table 1) lists the number of cache misses per lookup and space requirements as compared to the basic Bloom Filter, as well as whether or not deletion is supported. Of course, your work is more comparable to only the counting Bloom filter. (And, perhaps, comparable to HyperLogLog, which, while not optimized for it, provides a AMQ interface with counting.)

Thanks!

**Comment by prashantpandey** [comment]
Hi Daniel,

Yeah, we have a paper to accepted in SIGMOD 2017. I will share the link once it's published. 
We have an exhaustive comparison against AMQs (Cuckoo filter, Bloom filter, Quotient filter) and Counting filters (Counting Bloom filter) in the paper.

Thanks
Prashant

**Comment by prashantpandey** [comment]
Hi Daniel,

Here is the paper: http://dl.acm.org/citation.cfm?id=3035963.
