### ISSUE TITLE
uint128_t invertible hash

### ISSUE THREAD

**Issue by calvin2021y** [splatlab/cqf#17]
Is is possible to modify https://github.com/splatlab/cqf/blob/master/src/hashutil.c#L132 to add a uint128_t version ?

**Comment by rtjohnso** [comment]
Do you just want a 128-bit invertible hash function, or are you interested
in storing 128-bit hashes in the CQF.

Also, note that hash_64() has the very strong property that it is
invertible on every range of the form [0, 2^k).  Do you need that, or just
invertibility on 128-bit values?

I think adding 128-bit support to the entire CQF would be useful but a lot
of work.  It is not currently on the roadmap.

I believe extending the hash_64 function to 128-bit values would be
straightforward, although I think you will need to modify the inverse
function.  It's also not clear whether it would be a good hash function.
If you do so, please let us know.  I'd be curious to see the results.

Best,
Rob

**Comment by calvin2021y** [comment]
Thanks for the great work.  

>>> Also, note that hash_64() has the very strong property that it is
invertible on every range of the form [0, 2^k).  Do you need that, or just
invertibility on 128-bit values?

Yes, this is what I am interested in.

```c
uint128_t hash_128(uint64_t key, uint128_t mask);
uint128_t hash_128i(uint64_t key, uint128_t mask);
```

mask between (2^65-1) ~ (2^128-1).  so I can choice diff mask for diff tasks.

I guess this can be a good start,  add storing 128-bit hashes also useful but right now hash_128/hash_128i will be enough for me.

**Comment by calvin2021y** [comment]
I am not sure how the magic work.  for example where come from the number `14933078535860113213ull`. 

storing  hashes and invertible will be perfect.   result should still in range [0, 2^k)

**Comment by rtjohnso** [comment]
Hi calvin,  Since 128-bit support in the QF is not on the roadmap, I don't think there's a good reason for us to implement a 128-bit version of that hash function.

But if you want to take a stab at it, you can find documentation of the design of that hash function here: https://gist.github.com/badboy/6267743

Best,
Rob
