### ISSUE TITLE
Fixed Bits Per Slot

### ISSUE THREAD

**Issue by shokrof** [splatlab/cqf#6]
Hi,
I am trying to create cqf having key remainders of size less than 8 bits. From the usage example(main.c), the number of hash bits equals 8+ qbits. Changing the value 8 to other value leads to assertion error("(BITS_PER_SLOT == 0 || BITS_PER_SLOT == qf->bits_per_slot)"). However, Changing  BITS_PER_SLOT in gqf.h from 8 to 0 bypass the assertion and the code passes the testcase written in main.c.

I want to make sure is it safe to set BITS_PER_SLOT to 0. I am curious if you did enough tests for this situation.

**Comment by prashantpandey** [comment]
Hi @shokrof,

You did the right thing. When `BITS_PER_SLOT` in `gqf.h` is set to 0 then it means that it will be set during runtime. We do this whenever we don't know the size of the remainders at compile time.

Thanks,
Prashant

**Comment by shokrof** [comment]
Hi Prashant,
Thanks for your time. I checked your code,  and I found that the slots array is of type uint8_t.
 Suppose, I choose the size of the key remainder to be equal to 6. will there be a 2 bits waste at every slot?
Or you do "the complex bit operations" to create an array of 6-bits integers using uint8_t array.
Regards,
Mostafa

**Comment by rtjohnso** [comment]
There will not be any wastage.

Best,
Rob
